function [outDs outBoard] = Init(config)
    initialTurns = 2;

    Allele1 = [ones(1,config.Initial_AA_Phenotype),...
                 ones(1,config.Initial_Aa_Phenotype),...
                 ones(1,config.Initial_aa_Phenotype)+1];
    Allele2 = [ones(1,config.Initial_AA_Phenotype),...
                 ones(1,config.Initial_Aa_Phenotype)+1,...
                 ones(1,config.Initial_aa_Phenotype)+1];    
    
    
    outDs = struct('Id',1:config.NumOfCreatures,...
                'Row',zeros(1,config.NumOfCreatures),...
                'Col',zeros(1,config.NumOfCreatures),...
                'Sex',mod(1:config.NumOfCreatures,2) + 1,...
                'Age',ones(1,config.NumOfCreatures),...
                'Allele1',Allele1,...
                'Allele2',Allele2,...
                'Turns',ones(1,config.NumOfCreatures) * initialTurns);    

    %Generate random unique positions for each creature:
    randomPositionIndexes = randperm(config.BoardDim*config.BoardDim);
    limitedPositionIdxs = randomPositionIndexes(1:config.NumOfCreatures);
    [outDs.Row outDs.Col] = ind2sub([config.BoardDim config.BoardDim],limitedPositionIdxs); 

    outBoard = zeros(config.BoardDim*config.BoardDim);
    outBoard(limitedPositionIdxs) = outDs.Id;   
end